### ISSUE TITLE
why use the nn.Embedding rather than something pre-trained

### ISSUE THREAD

**Issue by Abbyyan** [HLTCHKUST/Mem2Seq#17]
Sorry to bother you, but i really want to ask when encoding the words , why you use the nn.Embedding rather than use a pre-trained Embedding such as Glove? Hope you can help me with this question. Thank you very much !

**Comment by andreamad8** [comment]
Hi @Abbyyan, 

we did not use any pre-trained word embeddings because this task has a lot of Named-Entity which are actually not present in Glove vocabulary. 

Anyway, would be interesting to try the newest contextualized word embeddings (e.g. CLOVA, ELMO, BERT, GPT-2 etc.).

I hope this help. 

Best 

Andrea

ps: nn.Embedding is needed also for pre-trained word embeddings.
